name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: pip install pytz

      - name: Run unit tests
        run: python -m unittest discover -s tests

  deploy:
    name: Deploy to EC2
    needs: test
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ec2_rsa
          chmod 600 ~/.ssh/ec2_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy changes to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd summarize-meetings
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            exit
          EOF